name: Test Linux x86_64 - build of Rust examples

on:
  workflow_dispatch:
    inputs:
      rust_build_branch:
        description: 'Branch with test scripts'
        required: true
        default: 'main'
      toolchain_version:
        description: 'Version of Rust IDF toolchain'
        required: true
        default: '1.60.0.0'
      esp_idf_version:
        description: 'Version of ESP-IDF for the build'
        required: true
        default: 'release/v4.4'
      project:
        description: 'Name of project for the build'
        required: true
        default: 'rust-esp32-std-demo'
      project_repo:
        description: 'Git repository of the project'
        required: true
        default: 'https://github.com/ivmarkov/rust-esp32-std-demo.git'
      features:
        description: 'Features for the build, space separated list'
        required: true
        default: 'native'
      test_mode:
        description: 'Testing mode: build, flash, monitor'
        required: true
        default: 'build'

jobs:
  build-idf-rust-examples:
    name: Build IDF Rust Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ xtensa-esp32-espidf, xtensa-esp32s2-espidf, xtensa-esp32s3-espidf, riscv32imc-esp-espidf ]
      fail-fast: false

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rust_build_branch }}
      - uses: ./.github/actions/tools/setup-libudev
      - uses: ./.github/actions/tools/setup-python
      - uses: ./.github/actions/tools/setup-ninja
      - name: Test Rust toolchain by compiling STD demo
        run: |
          ./test-rust-toolchain.sh --toolchain-version ${{ github.event.inputs.toolchain_version }} \
          --project ${{ github.event.inputs.project }} \
          --project-url ${{ github.event.inputs.project-url }} \
          --target ${{ matrix.target }} \
          --features ${{ github.event.inputs.features }}
